// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9jtAds3OtgmVj7S3-mnLwULL1HoYrsGo',
    appId: '1:226791606258:web:f83786059ccc839788cd6b',
    messagingSenderId: '226791606258',
    projectId: 'my-fit-healthdb',
    authDomain: 'my-fit-healthdb.firebaseapp.com',
    storageBucket: 'my-fit-healthdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgPua5qlJqic2Y3o7MwTl24izZIJlewtc',
    appId: '1:226791606258:android:6ee617ecbadc7d6f88cd6b',
    messagingSenderId: '226791606258',
    projectId: 'my-fit-healthdb',
    storageBucket: 'my-fit-healthdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK_B_gJ75SZDQZ2Gtj5kfW61rc4PONino',
    appId: '1:226791606258:ios:78ca9a219a8f534988cd6b',
    messagingSenderId: '226791606258',
    projectId: 'my-fit-healthdb',
    storageBucket: 'my-fit-healthdb.appspot.com',
    iosBundleId: 'com.example.fithealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK_B_gJ75SZDQZ2Gtj5kfW61rc4PONino',
    appId: '1:226791606258:ios:f18cfcf8a999488388cd6b',
    messagingSenderId: '226791606258',
    projectId: 'my-fit-healthdb',
    storageBucket: 'my-fit-healthdb.appspot.com',
    iosBundleId: 'com.example.fithealth.RunnerTests',
  );
}
